version: 0.0
os: linux
files:
  - source: publish/tiwari
    destination: /home/ubuntu/tiwari
    overwrite: true
    file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
